spring.application.name=lifeRPG-backend
spring.datasource.url=jdbc:postgresql://ep-quiet-dream-ax0jns0n-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oFSV7KQAULE2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect